In [46]:
import numpy as np

1. Array Creation & Properties

In [54]:
#Create a 1-D NumPy array containing integers from 10 to 49.
arr1D = np.arange(10,50)
arr1D

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [56]:
#Reshape the array into a 5×8 matrix.
arr2D = arr1D.reshape(5,8)
arr2D

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
#Print and interpret:
#shape
print(arr2D.shape)
#size
print(arr2D.size)
#ndim
print(arr2D.ndim)
#dtype
print(arr2D.dtype)

(5, 8)
40
2
int64


In [64]:
#Convert the array from integer to float.
arr1D.astype(np.float64, casting='same_kind')
arr2D.astype(np.float64, casting='same_kind')

array([[10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30., 31., 32., 33.],
       [34., 35., 36., 37., 38., 39., 40., 41.],
       [42., 43., 44., 45., 46., 47., 48., 49.]])

2. Indexing & Slicing

In [71]:
#Extract the first row and the last row of the matrix.
print(arr2D[:1])
print(arr2D[-1:])

[[10 11 12 13 14 15 16 17]]
[[42 43 44 45 46 47 48 49]]


In [72]:
#Extract the first two columns.
arr2D[:,:2]

array([[10, 11],
       [18, 19],
       [26, 27],
       [34, 35],
       [42, 43]])

In [79]:
#Slice a 3×3 sub-matrix from the center.
arr2D_sub = arr2D[2:5,3:6]
arr2D_sub

array([[29, 30, 31],
       [37, 38, 39],
       [45, 46, 47]])

In [85]:
#Modify a sliced element and observe whether the original array changes.
arr2D_sub[0,2] = 45
arr2D_sub

array([[29, 30, 45],
       [37, 38, 39],
       [45, 46, 47]])

In [86]:
#Demonstrate the difference between a view and a copy.
'''View - 
It creates array differently by changing metadata like stride and dtype
without changing the data buffer. The newly created arrays are called views.

As the data buffer reamins the same so any changes in the view reflects in the original copy.

It can be forced through ndarray.view method.



Copy - 
When a new array is created by duplicating the data buffer as well as the metadata, it is called copy.

Any changes made to the copy do not reflect on the original array.

Copy is slower and  memory-consuming but sometimes necessary

It can be forced by ndarray.copy'''

'View - \nIt creates array differently by changing metadata like stride and dtype\nwithout changing the data buffer. The newly created arrays are called views.\n\nAs the data buffer reamins the same so any changes in the view reflects in the original copy.\n\nIt can be forced through ndarray.view method.\n\n\n\nCopy - \nWhen a new array is created by duplicating the data buffer as well as the metadata, it is called copy.\n\nAny changes made to the copy do not reflect on the original array.\n\nCopy is slower and  memory-consuming but sometimes necessary\n\nIt can be forced by ndarray.copy'

3. Boolean Masking & Conditional Updates

In [95]:
#Generate a NumPy array of 25 random integers between 1 and 100.
arr = (np.linspace(1,100,25)).astype('int64')
arr

array([  1,   5,   9,  13,  17,  21,  25,  29,  34,  38,  42,  46,  50,
        54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [97]:
#Select all elements greater than 60.
arr[arr > 60]

array([ 62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [99]:
#Replace values below 40 with 0.
arr[arr < 40] = 0
arr

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  42,  46,  50,
        54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [113]:
#Count how many values lie between 50 and 80.
np.sum((arr > 50) & (arr < 80))

7

4. Vectorized Operations
(This section is especially important for recruiters.)

In [137]:
#Create an array of 100,000 random values.
#np.random.rand(100000) - Deprecated
#np.random.default_rng().random(100000) # For float
arr_rand = np.random.default_rng().integers(0,101,100000) # For Integers
arr_rand

array([ 8, 53, 84, ..., 56,  4, 14])

In [142]:
#Compute the square of each element using a Python loop.
for i in arr_rand:
    i*i

In [134]:
#Compute the square using NumPy vectorization.
#vectorization method means to perform operation on an array at once 
#without any loop
arr_rand_sq = np.square(arr_rand)
arr_rand_sq

In [18]:
#Measure execution time for both approaches.
#Operations like arr**2 and np.square(arr) are significantly faster than looping through a list because they are implemented in highly optimized C.

In [19]:
#Explain why vectorized operations are faster.
#np.vectorize() exists to convert standard Python functions into vectorized-like functions, it is primarily for convenience and does not provide the same performance boost as the native methods mentioned

5. Broadcasting

In [148]:
#Create a 4×3 matrix filled with random values.
a = (np.random.default_rng().integers(20,40,12)).reshape(4,3)
a

array([[22, 29, 20],
       [35, 29, 21],
       [28, 31, 37],
       [39, 34, 25]])

In [149]:
#Create a 1-D array of length 3.
b = np.arange(3)

In [151]:
#Add the 1-D array to the matrix using broadcasting.
a.shape
b.sh

(4, 3)

In [23]:
#Explain how NumPy matches dimensions internally.

6. Aggregations & Axis Operations

In [24]:
#Compute the overall mean, median, and standard deviation.

In [25]:
#Compute row-wise means.

In [26]:
#Compute column-wise sums.

In [27]:
#Identify the maximum value in each column.

7. Normalization & Scaling

In [28]:
#Normalize an array using min-max scaling.

In [29]:
#Normalize the same array using z-score standardization.

In [30]:
#Compare the output ranges and distributions.

8. Linear Algebra Basics

In [31]:
#Create two matrices with compatible dimensions.

In [32]:
#Perform matrix multiplication using @.

In [33]:
#Compute transpose and verify shapes.

In [34]:
#Compute determinant and inverse (where possible).

In [35]:
#Validate the inverse using matrix multiplication.

9. Reshaping & Stacking

In [36]:
#Flatten a matrix using:

#flatten()

#ravel()

#Explain the difference in behavior.

In [37]:
#Stack two arrays vertically.

In [ ]:
#Stack two arrays horizontally.

10. Random Module & Reproducibility

In [38]:
#Set a random seed and generate random values.

In [39]:
#Re-run the code and verify reproducibility.

In [40]:
#Generate samples from a normal distribution.

In [41]:
#Compare mean and standard deviation with theoretical values.

11. Mini Practical Exercise (Optional but Strong)

In [45]:
#Create a synthetic dataset (rows = observations, columns = features).

In [43]:
#Normalize each feature independently.

In [44]:
#Compute feature-wise statistics.

In [ ]:
#Identify outliers using z-score logic and replace them.